[program:ear_service]
# CHANGED: Now points to the specific project folder
directory=/home/jzay/personal_website/projects/ear

# CHANGED: Runs 'service:app' (since we renamed ear_service.py to service.py)
command=/home/jzay/personal_website/.venv/bin/gunicorn 'service:app' --bind 127.0.0.1:5001 --workers 1 --timeout 120 --preload

user=jzay
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/personal_website/ear_service.err.log
stdout_logfile=/var/log/personal_website/ear_service.out.log
