[program:personal_website]
directory=/home/jzay/personal_website
command=/home/jzay/personal_website/.venv/bin/gunicorn 'app:create_app()' --bind 127.0.0.1:8000 --workers 3
user=jzay
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/personal_website/personal_website.err.log
stdout_logfile=/var/log/personal_website/personal_website.out.log
